format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
staged = "✚${count}"
modified = "●${count}"
untracked = "…${count}"
